FROM php:7.1.31-fpm-alpine3.9

#タイムゾーン設定
RUN apk --update add tzdata && \
    cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime && \
    apk del tzdata && \
    rm -rf /var/cache/apk/*

#PDOをインストール
RUN docker-php-ext-install pdo_mysql
RUN mkdir -p /var/command
ADD ./nginx/php/php.ini /usr/local/etc/php/php.ini
