version: '3'
services:
 gui:
    tty: true
    build:
       context: .
       dockerfile: Dockerfile_ubuntu
    devices:
         -  /dev/bus/usb/001/004
    volumes:
        - ./gui/:/opt
        - ./command/file:/var/command
    ports:
        - 3389:3389
    restart: always

 web:
   image: nginx:1.17.2-alpine-perl
   ports:
     - 80:80
   volumes:
     - ./nginx/html:/var/www/html
     - ./nginx/conf.d:/etc/nginx/conf.d
     - ./nginx/ssl:/etc/pki/tls/private

 fpm:
   build:
     context: .
     dockerfile: Dockerfile_php
     volumes:
       - ./nginx/html:/var/www/html

 db:
    image: mariadb:10.4
    ports:
     - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_USER: eemgmt
      MYSQL_PASSWORD: passwd
    volumes:
      - ./db/initdb:/docker-entrypoint-initdb.d
      - ./db/conf.d/:/etc/mysql/conf.d
      - ./db/mysql_data:/var/lib/mysql
    restart: always

 messages:
   build:
      context: .
      dockerfile: Dockerfile_flask
   tty: true
   volumes:
       - ./flask/:/opt
   restart: always

 linelogin:
   build:
      context: .
      dockerfile: Dockerfile_flask
   ports:
    - 10000:10000
   tty: true
   volumes:
       - ./linelogin/:/opt
   restart: always
