version: '3'
services:
 gui:
    tty: true
    build:
       context: .
       dockerfile: Dockerfile_ubuntu
    devices:
         -  /dev/bus/usb/001/004
    ports:
        - 3389:3389
    #command: bash -c "sh start.sh"
    #tty: true

 web:
   image: php:7.3.4-apache
   ports:
     - 80:80
     - 443:443
   volumes:
     - ./www:/var/www/html

 db:
  image: mariadb:10.4
  ports:
   - 3306:3306
  volumes:
   # 永続化
   - ./db/mysql_data:/var/lib/mysql
  environment:
   #データベースrootパスワード
   MYSQL_ROOT_PASSWORD: passwd
   MYSQL_DATABASE: EEmgmt
   #ユーザー
   MYSQL_USER: eemgmt
   MYSQL_PASSWORD: passwd
