version: '3'
services:
 gui:
    tty: true
    build:
       context: .
       dockerfile: Dockerfile_ubuntu
    devices:
         -  /dev/bus/usb/001/004
    volumes:
        - ./gui/:/opt
        - ./command/file:/var/command
    ports:
        - 3389:3389
    restart: always

 web:
   image: nginx:1.17.2-alpine
   ports:
     - 443:443
     - 8080:8080
   tty: true
   volumes:
    - ./nginx/html:/var/www/html
    - ./nginx/conf.d:/etc/nginx/conf.d
    - /etc/letsencrypt/live:/etc/letsencrypt/live
    - /etc/letsencrypt/archive:/etc/letsencrypt/archive
   environment:
     DOMAIN_NAME: ${DOMAIN_NAME}
   command: /bin/sh -c "envsubst '$$DOMAIN_NAME' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

 fpm:
   build:
     context: .
     dockerfile: Dockerfile_php
   volumes:
    - ./nginx/html:/var/www/html
   environment:
     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
     FROM_EMAIL: ${FROM_EMAIL}
     ID_EMAIL: ${ID_EMAIL}
     PASS_EMAIL: ${PASS_EMAIL}
     LINEAPI_TOKEN: ${LINEAPI_TOKEN}

 db:
    image: mariadb:10.4
    ports:
     - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db/initdb:/docker-entrypoint-initdb.d
      - ./db/conf.d/:/etc/mysql/conf.d
      - ./db/mysql_data:/var/lib/mysql
    restart: always

 messages:
   build:
      context: .
      dockerfile: Dockerfile_flask
   tty: true
   volumes:
       - ./flask/:/opt
   restart: always

 linelogin:
   build:
      context: .
      dockerfile: Dockerfile_flask
   tty: true
   volumes:
       - ./linelogin/:/opt
   environment:
     CHANNEL_ID: ${CHANNEL_ID}
     CHANNEL_SECREST: ${CHANNEL_SECREST}
     CALLBACK_URL: ${CALLBACK_URL}
     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
     CANCEL_CALLBACK_URL: ${CANCEL_CALLBACK_URL}
   restart: always

 linereply:
   build:
     context: .
     dockerfile: Dockerfile_linereply
   tty: true
   volumes:
     - ./linelogin/:/opt
   restart: always
