FROM php:7.3.4-apache

#タイムゾーン設定
ENV TZ Asia/Tokyo
RUN echo "${TZ}" > /etc/timezone \
   && dpkg-reconfigure -f noninteractive tzdata

ENV DEBIAN_FRONTEND noninteractive
#キーボード入力待ちをさせない
#PDOをインストール
RUN docker-php-ext-install pdo_mysql
RUN mkdir -p /var/command

#certbotインストール
RUN apt-get update
RUN apt-get install software-properties-common -y
RUN add-apt-repository universe -y
RUN add-apt-repository ppa:certbot/certbot -y
RUN apt-get update
RUN apt-get install certbot python-certbot-apache -y
RUN certbot certonly --webroot -w /var/www/html/ -d example.com -m sample@example.com --agree-tos -n --http-01-port 10000 --tls-sni-01-port10001


ADD ./apache2/php/php.ini /usr/local/etc/php/php.ini
