FROM  ubuntu:18.04
ENV DEBIAN_FRONTEND noninteractive
#キーボード入力待ちをさせない

RUN sed -i".bak" -e 's/\/\/us.archive.ubuntu.com/\/\/ftp.jaist.ac.jp/g' /etc/apt/sources.list
RUN apt update
RUN apt upgrade -y

RUN useradd -m test
RUN echo "test:passwd" | chpasswd
RUN gpasswd -a test sudo

RUN apt install -y tzdata
#timezone
ENV TZ=Asia/Tokyo

RUN apt install -y sudo python3-pip  python-pip  python3-tk fonts-noto  xrdp curl mate-desktop-environment-core mate-desktop-environment
RUN pip3 install netifaces mysql-connector-python slackweb
RUN pip install -U nfcpy
#RUN apt -y install mate-desktop-environment-core
#RUN apt -y install mate-desktop-environment

ENV DOCKERVERSION=18.03.1-ce
RUN curl -fsSLO https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKERVERSION}.tgz \
  && tar xzvf docker-${DOCKERVERSION}.tgz --strip 1 \
                 -C /usr/local/bin docker/docker \
  && rm docker-${DOCKERVERSION}.tgz

RUN service xrdp start

CMD service xrdp start
CMD rm /var/run/xrdp/xrdp.pid
CMD service xrdp restart && tail -f /dev/null
