version: '3'
services:
 gui:
    tty: true
    build:
       context: .
       dockerfile: Dockerfile_ubuntu
    devices:
         -  /dev/bus/usb/001/004
    ports:
        - 3389:3389

 web:
   build:
      context: .
      dockerfile: Dockerfile_php
   ports:
     - 80:80
     - 443:443
   volumes:
     - ./apache2/www:/var/www/html
     - ./apache2/conf:/etc/apache2
     - ./apache2/ssl:/etc/ssl

  db:
    image: mariadb:10.4
    ports:
     - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_USER: eemgmt
      MYSQL_PASSWORD: passwd
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - ./db/mysql_data:/var/lib/mysql
