version: '3'
services:
	ubuntu:
		image: ubuntu:16.04
		ports:
			- "3389:3389"
			- "80:80"
			- "443:443"
			
	db:
		image: mariadb:10.3.0
		ports:
			- "3389:3389"
		volumes:
            # 永続化
            - ./db/mysql_data:/var/lib/mysql
		environment:
			#データベースrootパスワード
			MYSQL_ROOT_PASSWORD: passwd
			MYSQL_DATABASE: EEmgmt
			#ユーザー
			MYSQL_USER: eemgmt
			MYSQL_PASSWORD: passwd
			