CREATE DATABASE EEmgmt;
USE EEmgmt;

CREATE TABLE login(
userid INTEGER NOT NULL,
username VARCHAR(100) NOT NULL,
pass VARCHAR(300) NOT NULL,
addcard INTEGER NOT NULL,
editcard INTEGER NOT NULL,
sendnotice INTEGER NOT NULL,
viewexit INTEGER NOT NULL,
viewloginlog INTEGER NOT NULL,
deletelog INTEGER NOT NULL,
initialize INTEGER NOT NULL,
setmail INTEGER NOT NULL,
shutdown INTEGER NOT NULL,
edituser INTEGER NOT NULL,
PRIMARY KEY (userid,username));

CREATE TABLE service_user(
userid INTEGER NOT NULL,
idm VARCHAR(30) NOT NULL,
name VARCHAR(30) NOT NULL,
notice VARCHAR(30) NOT NULL,
address VARCHAR(300),
PRIMARY KEY (userid,idm));
